# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uf',
            options={'managed': False, 'ordering': ['date']},
        ),
    ]
